### ISSUE TITLE
Null referencing in bleptr

### ISSUE THREAD

**Issue by decltypeme** [decltypeme/mips-simulator#22]
Load the test files here and keep pressing "Advance one step"
[regexRule.txt](https://github.com/decltypeme/mips-simulator/files/60445/regexRule.txt)
[test1.txt](https://github.com/decltypeme/mips-simulator/files/60444/test1.txt)

**Comment by hussam-a** [comment]
I thought i told ya we fixed it :p

_Hussam Ashraf El Araby_
Computer Engineering Undergraduate
American University in Cairo
